from pathlib import Path
p=Path('src/components/admin/AssistenteVisionPanel.tsx')
s=p.read_text()
def rep(old,new,count=1):
 global s
 if s.count(old)!=count: raise SystemExit(f'guard expected {count}, got {s.count(old)}: {old[:80]!r}')
 s=s.replace(old,new,count)
rep("  const [primeActive, setPrimeActive] = useState(false);", "  const [primeActive, setPrimeActive] = useState(false);\n  const [primeConfig, setPrimeConfig] = useState<{ valor_mensalidade:number; desconto_percentual:number; frete_gratis_minimo:number } | null>(null);\n  const [activeCoupon, setActiveCoupon] = useState<{ codigo:string; tipo:string; valor:number } | null>(null);")
rep("      const [ord, prime, parc, fb, st] = await Promise.all([", "      const [ord, prime, coupon, parc, fb, st] = await Promise.all([")
rep("        supabase.from('vision_prime_config').select('ativo').eq('organization_id', organizationId).maybeSingle(),", "        supabase.from('vision_prime_config').select('ativo,valor_mensalidade,desconto_percentual,frete_gratis_minimo').eq('organization_id', organizationId).maybeSingle(),\n        supabase.from('cupons').select('codigo,tipo,valor').eq('organization_id', organizationId).eq('ativo', true).order('created_at', { ascending: false }).limit(1).maybeSingle(),")
rep("      setPrimeActive(Boolean(prime.data?.ativo));", "      setPrimeActive(Boolean(prime.data?.ativo));\n      setPrimeConfig(prime.data?.ativo ? { valor_mensalidade:Number((prime.data as any).valor_mensalidade)||0, desconto_percentual:Number((prime.data as any).desconto_percentual)||0, frete_gratis_minimo:Number((prime.data as any).frete_gratis_minimo)||0 } : null);\n      setActiveCoupon(coupon.data ? { codigo:(coupon.data as any).codigo, tipo:(coupon.data as any).tipo, valor:Number((coupon.data as any).valor)||0 } : null);")
rep("        template: `Olá [Nome], sua última escolha em ${storeName} está com saudade! 😋 Volte hoje com o cupom *VOLTE15* e ganhe 10% OFF no seu pedido.`,", "        template: activeCoupon ? `Olá [Nome], sentimos sua falta em ${storeName}! 😋 Volte e aproveite o cupom *${activeCoupon.codigo}* (${activeCoupon.tipo === 'porcentagem' ? `${activeCoupon.valor}% de desconto` : `${brl(activeCoupon.valor)} de desconto`}).` : `Olá [Nome], sentimos sua falta em ${storeName}! 😋 Que tal fazer um novo pedido hoje?`,")
rep("        template: `Oi [Nome]! Que tal turbinar seu pedido? 🍔🍟 Adicione nosso *Combo do Dia* e leve batata + refri por só R$ 15. Aproveite!`,", "        template: `Oi [Nome]! Que tal turbinar seu próximo pedido em ${storeName}? 🍔🍟 Confira os combos e adicionais disponíveis no cardápio.`,")
rep("        description: 'Você ainda não ativou o clube de assinatura. Lojas com Prime ativo aumentam em até 30% a recorrência mensal.',", "        description: 'Você ainda não ativou o clube de assinatura. Configure mensalidade e benefícios antes de divulgá-lo aos clientes.',")
rep("        template: `🌟 Cliente VIP! Apresentamos o *Vision Prime* em ${storeName}: por R$ 19,90/mês você ganha 10% OFF em todos os pedidos e frete grátis. Assine hoje mesmo!`,", "        template: `🌟 Cliente VIP! Em breve você poderá conhecer os benefícios do *Vision Prime* em ${storeName}.`,")
rep("        template: `Olá [Nome], você é um dos nossos clientes mais especiais! 💎 Queremos te convidar para o *Vision Prime*: 10% OFF em todos os pedidos + frete grátis. Apenas R$ 19,90/mês. Quer fazer parte?`,", "        template: primeConfig ? `Olá [Nome], você é um dos nossos clientes mais especiais! 💎 Conheça o *Vision Prime* em ${storeName}: ${primeConfig.desconto_percentual > 0 ? `${primeConfig.desconto_percentual}% de desconto` : 'benefícios exclusivos'}${primeConfig.frete_gratis_minimo >= 0 ? ` e frete grátis conforme a regra configurada` : ''}. Mensalidade: ${brl(primeConfig.valor_mensalidade)}. Quer fazer parte?` : `Olá [Nome], você é um dos nossos clientes mais especiais! 💎 Conheça o *Vision Prime* em ${storeName}.`,")
rep("  }, [orders, primeActive, parceriasAtivas, feedback, stats, storeName]);", "  }, [orders, primeActive, primeConfig, activeCoupon, parceriasAtivas, feedback, stats, storeName]);")
p.write_text(s)
print('assistant configured-offer guards applied')
