-- Phase 67: restore secure Assistente Vision feedback/history core.
create table if not exists public.assistente_vision_feedback(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,suggestion_key text not null,action text not null check(action in('approved','dismissed','sent')),reason text not null default '',message_sent text not null default '',created_at timestamptz not null default now());
create index if not exists idx_assistente_vision_feedback_org on public.assistente_vision_feedback(organization_id,created_at desc); alter table public.assistente_vision_feedback enable row level security;
create policy "owner read assistente feedback" on public.assistente_vision_feedback for select to authenticated using(public.usuario_dono_org(organization_id,(select auth.uid())) or public.eh_super_admin((select auth.uid())));
create policy "owner insert assistente feedback" on public.assistente_vision_feedback for insert to authenticated with check(public.usuario_dono_org(organization_id,(select auth.uid())) or public.eh_super_admin((select auth.uid())));
revoke all on public.assistente_vision_feedback from anon; grant select,insert on public.assistente_vision_feedback to authenticated;
create table if not exists public.ai_suggestions_history(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,suggestion_key text not null,category text not null default '',title text not null default '',reason text not null default '',template text not null default '',priority integer not null default 0,audience_size integer not null default 0,status text not null default 'pending' check(status in('pending','approved','dismissed','sent')),dismiss_reason text not null default '',notifications_sent integer not null default 0,conversions integer not null default 0,generated_at timestamptz not null default now(),acted_at timestamptz,dispatched_at timestamptz,last_conversion_check timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists idx_ai_suggestions_history_org on public.ai_suggestions_history(organization_id,created_at desc); alter table public.ai_suggestions_history enable row level security;
create policy "owner read ai suggestion history" on public.ai_suggestions_history for select to authenticated using(public.usuario_dono_org(organization_id,(select auth.uid())) or public.eh_super_admin((select auth.uid())));
create policy "owner insert ai suggestion history" on public.ai_suggestions_history for insert to authenticated with check(public.usuario_dono_org(organization_id,(select auth.uid())) or public.eh_super_admin((select auth.uid())));
revoke all on public.ai_suggestions_history from anon; grant select,insert on public.ai_suggestions_history to authenticated;
create or replace function public.ai_suggestion_stats(_org uuid) returns table(category text,conversion_rate numeric,total_conversions bigint,total_sent bigint,total_dismissed bigint) language plpgsql security definer set search_path='' as $$begin if auth.uid() is null or (not public.usuario_dono_org(_org,auth.uid()) and not public.eh_super_admin(auth.uid())) then raise exception 'forbidden' using errcode='42501'; end if; return query select h.category,case when count(*) filter(where h.status='sent')>0 then round(100.0*sum(h.conversions)::numeric/count(*) filter(where h.status='sent'),2) else 0 end,sum(h.conversions)::bigint,count(*) filter(where h.status='sent')::bigint,count(*) filter(where h.status='dismissed')::bigint from public.ai_suggestions_history h where h.organization_id=_org group by h.category; end$$;
revoke all on function public.ai_suggestion_stats(uuid) from public,anon; grant execute on function public.ai_suggestion_stats(uuid) to authenticated;
